language: java
jdk:
  - openjdk8
sudo: required

env:
  - ORBEON_URL_CE=https://github.com/orbeon/orbeon-forms/releases/download/tag-release-2017.1-ce/orbeon-2017.1.201706222342-CE.zip

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - bash ./script/getCleanedOrbeon.sh $ORBEON_URL_CE
  - mvn clean install
  - docker build -t laurentc35/stromae .

deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push laurentc35/stromae
    on:
      branch: master

  - skip_cleanup: true
    provider: script
    script: kubectl --token $K8S_TOKEN --server $K8S_SERVER --insecure-skip-tls-verify rollout restart deployment/stromae -n pogues-eno
    on:
      branch: master
